---
- hosts: all
  remote_user: root
  vars:
    # packages_repository_base_url: "http://10.0.2.2:8080"
  tasks:
  - name: Make sure apt-transport-https is installed
    apt:
      pkg: "apt-transport-https"
      state: installed

  - name: Add Docker repository key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: Add Docker repository and update apt cache
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo debian-jessie main"
      update_cache: yes
      state: present

  - name: Install docker-engine
    apt:
      pkg: "docker-engine"
      state: installed

  - debug: hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  # - name: Update workflow job script with docker host IP
    # command: sed -i "s/62\.210\.100\.33/$(ip -f inet addr show eth1 | grep -Po 'inet \K[\d.]+')/g" /vagrant/workflow-job
  #  command: sed -i "s/62\.210\.100\.33/$(ip -o -4 addr show dev eth1 | awk -F '[ /]+' '/global/ {print $4}')/g" /vagrant/workflow-job

  #- name: create self-signed SSL cert
  #  command: openssl req -subj "/C=FR/ST=Paris/L=La Défense/O=Linagora OpenPaas/CN=linagora.com" -out CSR.csr -new -newkey rsa:2048 -nodes -keyout privateKey.key
  #- name: export self-signed SSL cert public key
  #  command: openssl rsa -in privateKey.key -outform PEM -pubout -out public.pem

  - name: build jenkins HTTPS cert key docker container
    command: docker build -f DockerFileKeyContainer -t keys .
  - name: run docker container hosting jenkins cert keys
    command: docker run -v /keys --name keys keys

  - name: Build jenkins server Docker container
    command: docker build --tag myjenkins .
  - name: update env file with Jenkins host name
    command: sed -i 's/URL$/http\:\/\/localhost/g' env.file
#  - name: Run Jenkins as a docker container
#    command: docker rm -f jks
  - name: Run Jenkins as a docker container
    command: docker run -d -p 8080:8080 --volumes-from keys --env-file=./env.file --name jks myjenkins
